insert into ShopAddress values('JohnBC', 'Saint John Av.', '150', 'Vanvouver', 'BC')
insert into ShopAddress values('JohnNB', 'Eric St.', '84', 'Moncton', 'NB')
insert into ShopAddress values('JohnAB', 'Vicent St.', '1024', 'Calgary', 'AB')
insert into ShopAddress values('JohnSK', 'Famous St.', '14', 'Saskatoon', 'SK')
insert into ShopAddress values('JohnMB', 'George Av.', '1024', 'Winnipeg', 'MB')